/teleop_twist_joy_node:
  ros__parameters:
    axis_angular:
      pitch: -1 #not set
      roll: -1 #not set
      yaw: 0 #LS_X
    axis_linear:
      x: 1 #LS_Y
      y: -1 #not set
      z: -1 #not set
    enable_button: 0 #A
    enable_turbo_button: -1 # not set
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    require_enable_button: true
    scale_angular:
      pitch: 0.0
      roll: 0.0
      yaw: 0.5
    scale_angular_turbo:
      pitch: 0.0
      roll: 0.0
      yaw: 1.0
    scale_linear:
      x: 0.5
      y: 0.0
      z: 0.0
    scale_linear_turbo:
      x: 1.0
      y: 0.0
      z: 0.0
    use_sim_time: false

